### ISSUE TITLE
Suggestion for yet another but helpful TF Certification Training course for beginners by A Cloud Guru

### ISSUE THREAD

**Issue by acnjdl** [ak-org/TFDevCert#4]
TensorFlow Developer Certificate Exam Prep by Adam Vincent @ A Cloud Guru

https://learn.acloud.guru/course/tensorflow-developer-certificate-exam-prep/dashboard

I found the sequencing of his chapters organization very logical and he is a great instructor. In about 14 hours including few labs this is a very useful course for beginners to ML and TF.

**Comment by ak-org** [comment]
Thanks, I will add the link.
